const lessons = [
  {
    title: "CVC",
    words: [
      { en: "jab", zh: "猛擊" },
      { en: "rim", zh: "邊緣" },
      { en: "sag", zh: "下垂" },
      { en: "pod", zh: "豆莢" },
      { en: "ram", zh: "公羊" },
      { en: "hog", zh: "豬" },
      { en: "vat", zh: "大桶" },
      { en: "zap", zh: "迅速擊打" },
      { en: "nag", zh: "嘮叨；惹人煩" },
      { en: "clef", zh: "音譜記號" },
    { en: "clod", zh: "土塊；笨人" },
    { en: "clan", zh: "氏族" },
    { en: "flak", zh: "抨擊；防空炮火" },
    { en: "blob", zh: "一團" },
    { en: "blip", zh: "短暫訊號" },
    { en: "fret", zh: "煩惱；品格" },
    { en: "drat", zh: "該死！（感嘆）" },
    { en: "brim", zh: "邊緣；帽檐" },
      { en: "crypt", zh: "地窖；神秘地方" },
      { en: "brisk", zh: "輕快的" },
      { en: "crept", zh: "爬行（過去式）" },
      { en: "bluff", zh: "虛張聲勢" },
      { en: "grunt", zh: "咕噥聲" },
      { en: "blond", zh: "金髮的" },
    { en: "clamp", zh: "夾鉗；夾住" },
    { en: "crest", zh: "頂部；波峰" }
    ]
  },
  {
    title: "sh ch tch th ph",
    words: [
      { en: "shrub", zh: "灌木" },
      { en: "shack", zh: "簡陋小屋" },
       { en: "scamp", zh: "調皮鬼" },
     { en: "shun", zh: "避開" },
      { en: "slosh", zh: "濺動" },
      { en: "chill", zh: "寒冷" },
      { en: "filch", zh: "偷竊" },
      { en: "mulch", zh: "覆蓋層" },
      { en: "fetch", zh: "取回" },
      { en: "clutch", zh: "緊抓" },
      { en: "notch", zh: "刻痕" },
      { en: "snatch", zh: "搶奪" },
      { en: "thud", zh: "砰的一聲" },
      { en: "throb", zh: "跳動" },
      { en: "thrift", zh: "節儉" },
      { en: "thatch", zh: "茅草屋頂" },
      { en: "froth", zh: "泡沫" },
      { en: "glyph", zh: "符號" },
      { en: "lymph", zh: "淋巴" }

   ]
  },
{
    title: "Open Syllable (1)",
    words: [
      { en: "shy", zh: "害羞的" },
      { en: "sly", zh: "狡猾的" },
      { en: "thy", zh: "你的" },
      { en: "ply", zh: "層" },
      { en: "fry", zh: "油炸" },
{ en: "me", zh: "我" },
{ en: "he", zh: "他" },
{ en: "she", zh: "她" },
{ en: "we", zh: "我們" },
{ en: "be", zh: "是" },
{ en: "hi", zh: "你好（打招呼）" },
{ en: "my", zh: "我的" },
{ en: "by", zh: "在…旁邊；被" },
{ en: "cry", zh: "哭" },
{ en: "fly", zh: "飛" },
{ en: "dry", zh: "乾的" },
{ en: "try", zh: "嘗試" },
{ en: "go", zh: "去" },
{ en: "no", zh: "不" },
{ en: "so", zh: "所以" },
{ en: "yo", zh: "打招呼" },
{ en: "flu", zh: "流感" },
{ en: "pro", zh: "專業人士" }
    ]
  },
{
  title: "sc sk sp st",
  words: [
    { en: "stab", zh: "刺" },
    { en: "spill", zh: "灑出" },
    { en: "skit", zh: "短劇" },
    { en: "scab", zh: "痂" },
    { en: "stash", zh: "藏匿物" },
    { en: "spam", zh: "午餐肉" },
    { en: "skid", zh: "打滑" },
    { en: "scam", zh: "詐騙" },
    { en: "splat", zh: "啪的一聲" },
    { en: "skiff", zh: "小船" },
    { en: "scat", zh: "即興唱" },
    { en: "stench", zh: "惡臭" },
    { en: "sty", zh: "針眼" },
    { en: "stitch", zh: "縫" },
    { en: "scotch", zh: "蘇格蘭的" },
    { en: "scratch", zh: "抓"    }
  ]
},
{
  title: "ic ix ig eg",
  words: [
    { en: "lick", zh: "舔" },
    { en: "nix", zh: "否決" },
    { en: "fig", zh: "無花果" },
    { en: "peg", zh: "木釘" },
    { en: "frig", zh: "笨蛋" },
    { en: "keg", zh: "小桶" },
    { en: "brick", zh: "磚" },
    { en: "wig", zh: "假髮" },
    { en: "dregs", zh: "殘渣" },
    { en: "flick", zh: "輕彈" },
    { en: "brig", zh: "軍艦" },
    { en: "spick", zh: "整潔的" },
    { en: "stick", zh: "棍" },
    { en: "sprig", zh: "小枝" },
    { en: "nutmeg", zh: "肉豆蔻" },
    { en: "critic", zh: "評論家"
    }
  ]
},
{
  title: "a_e e_e i_e",
  words: [
    { en: "meme", zh: "迷因" },
    { en: "mime", zh: "默劇演員" },
    { en: "eve", zh: "前夕" },
    { en: "jibe", zh: "嘲諷；一致" },
    { en: "fave", zh: "最愛（口語）" },
    { en: "grebe", zh: "䴙䴘（鳥）" },
    { en: "chime", zh: "鐘聲" },
    { en: "thane", zh: "貴族（古）" },
    { en: "theme", zh: "主題" },
    { en: "strive", zh: "努力" },
    { en: "tame", zh: "馴服的" },
    { en: "chide", zh: "責備" },
    { en: "dale", zh: "山谷" },
    { en: "scale", zh: "規模；鱗片" },
    { en: "wipe", zh: "擦拭" },
    { en: "grime", zh: "污垢" },
    { en: "tike", zh: "頑童" },
    { en: "pipe", zh: "管子" },
    { en: "smite", zh: "重擊" },
    { en: "stake", zh: "木樁；賭注" },
    { en: "stile", zh: "梯門" },
    { en: "thine", zh: "你的（古）" },
    { en: "spine", zh: "脊椎" },
    { en: "phase", zh: "階段" }
  ]
},
{
  title: "o_e u_e",
  words: [
    { en: "bole", zh: "樹幹" },
    { en: "lute", zh: "魯特琴" },
    { en: "ruse", zh: "詭計" },
    { en: "dose", zh: "劑量" },
    { en: "fume", zh: "煙霧" },
    { en: "flute", zh: "長笛" },
    { en: "rune", zh: "古文字" },
    { en: "hone", zh: "磨利" },
    { en: "mule", zh: "騾" },
    { en: "glute", zh: "臀肌" },
    { en: "brute", zh: "野蠻的人" },
    { en: "throne", zh: "王座" },
    { en: "puke", zh: "嘔吐" },
    { en: "glute", zh: "臀大肌" },
    { en: "crude", zh: "粗糙的；原油" },
    { en: "drupe", zh: "核果"
    }
  ]
},
{
  title: "kn ng ing ink",
  words: [
    { en: "knack", zh: "竅門" },
    { en: "tong", zh: "夾子" },
    { en: "cling", zh: "緊貼" },
    { en: "whang", zh: "猛推" },
    { en: "rink", zh: "溜冰場" },
    { en: "knell", zh: "喪鐘聲" },
    { en: "gang", zh: "幫派" },
    { en: "sting", zh: "刺痛" },
    { en: "stink", zh: "惡臭" },
    { en: "knot", zh: "結" },
    { en: "throng", zh: "人群" },
    { en: "spring", zh: "春天" },
    { en: "chink", zh: "裂縫" },
    { en: "knit", zh: "編織" },
    { en: "shrink", zh: "縮小" },
{ en: "knife", zh: "刀" },
{ en: "knob", zh: "旋鈕" },
{ en: "link", zh: "連結" },
{ en: "think", zh: "思考" },
{ en: "song", zh: "歌曲" },
{ en: "hang", zh: "懸掛" },
{ en: "thing", zh: "東西" },
{ en: "ring", zh: "戒指；鈴聲" },
{ en: "king", zh: "國王" },
{ en: "wing", zh: "翅膀" },
{ en: "sing", zh: "唱歌" },
{ en: "bring", zh: "帶來" },
{ en: "swing", zh: "搖擺" },
{ en: "string", zh: "繩子" },
{ en: "pink", zh: "粉紅色" },
{ en: "knock", zh: "敲" },
{ en: "wink", zh: "眨眼" },
{ en: "blink", zh: "眨眼" },
{ en: "sink", zh: "下沉；洗手盆" },
{ en: "long", zh: "長的" },
{ en: "drink", zh: "喝" },
{ en: "brink", zh: "邊緣" },
{ en: "lung", zh: "肺" },
{ en: "strong", zh: "強壯的" }
  ]
},
{
  title: "qu gu wh wr",
  words: [
    { en: "quill", zh: "羽毛筆" },
    { en: "guilt", zh: "內疚" },
    { en: "wren", zh: "鷦鷯" },
    { en: "whip", zh: "鞭打" },
    { en: "quip", zh: "妙語" },
    { en: "guile", zh: "狡詐" },
    { en: "wrap", zh: "包裹" },
    { en: "whisk", zh: "攪拌" },
    { en: "quench", zh: "解渴" },
    { en: "guise", zh: "偽裝" },
    { en: "wry", zh: "諷刺的" },
    { en: "whig", zh: "輝格黨人（史）" },
    { en: "quake", zh: "震動" },
    { en: "wrench", zh: "扳手" },
    { en: "whang", zh: "猛擊（擬聲）" },
    { en: "quote", zh: "引用" },
    { en: "whine", zh: "抱怨" },
    { en: "wring", zh: "擰"
    }
  ]
},
{
  title: "ie -ie ee ea ue",
  words: [
    { en: "grief", zh: "悲痛" },
    { en: "vie", zh: "競爭" },
    { en: "twee", zh: "過分可愛的" },
    { en: "sheaf", zh: "一捆；一束" },
    { en: "flue", zh: "煙道" },
    { en: "shield", zh: "盾；保護" },
    { en: "knee", zh: "膝蓋" },
    { en: "knead", zh: "揉捏" },
    { en: "sprue", zh: "口腔病變" },
    { en: "chief", zh: "首領；主要的" },
    { en: "pie", zh: "餡餅" },
    { en: "wheeze", zh: "喘鳴聲" },
    { en: "wreath", zh: "花環" },
    { en: "clue", zh: "線索" },
    { en: "shriek", zh: "尖叫" },
    { en: "squeak", zh: "吱" },
    { en: "breathe", zh: "呼吸"
    }
  ]
},



{
  title: "ir ur er ar or",
  words: [
    { en: "shirk", zh: "逃避責任" },
    { en: "burst", zh: "爆裂" },
    { en: "fern", zh: "蕨類植物" },
    { en: "shard", zh: "碎片" },
    { en: "corpse", zh: "屍體" },
    { en: "stir", zh: "攪動；激起" },
    { en: "swerve", zh: "轉向；偏離" },
    { en: "slurp", zh: "啜食聲" },
    { en: "snarl", zh: "低吼；糾結" },
    { en: "Thor", zh: "雷神索爾" },
    { en: "whirl", zh: "旋轉" },
    { en: "scurf", zh: "頭皮屑" },
    { en: "berg", zh: "冰山" },
    { en: "scorn", zh: "輕蔑；鄙視" },
    { en: "mirth", zh: "歡樂" },
    { en: "spurb", zh: "虛構" },
    { en: "kerb", zh: "路緣" },
    { en: "larch", zh: "落葉松" },
    { en: "thorn", zh: "刺；荊棘"
    }
  ]
},
{
  title: "ei ai oi",
  words: [
    { en: "lei", zh: "花環" },
    { en: "raid", zh: "突襲" },
    { en: "coil", zh: "線圈" },
    { en: "veil", zh: "面紗" },
    { en: "stain", zh: "污漬；弄髒" },
    { en: "roil", zh: "攪亂；激怒" },
    { en: "vein", zh: "靜脈" },
    { en: "hoist", zh: "吊起；升起" },
    { en: "skein", zh: "一束紗線" },
    { en: "staid", zh: "沉穩的" },
    { en: "droid", zh: "機械人" },
    { en: "rein", zh: "韁繩；控制" },
    { en: "quail", zh: "鵪鶉；畏縮" },
    { en: "spoil", zh: "破壞；寵壞" },
    { en: "feint", zh: "假動作" },
    { en: "wraith", zh: "幽魂" },
    { en: "strait", zh: "海峽" },
    { en: "quoits", zh: "套環遊戲"
    }
  ]
},
{
  title: "ew",
  words: [
    { en: "dew", zh: "露水" },
    { en: "slew", zh: "大量；猛轉（過去式）" },
    { en: "screw", zh: "螺絲；擰" },
    { en: "skew", zh: "歪斜；扭曲" },
    { en: "brew", zh: "釀造" },
    { en: "blew", zh: "吹（過去式）" },
    { en: "stew", zh: "燉菜；燉煮" },
    { en: "flew", zh: "飛（過去式）" },
    { en: "shrew", zh: "鼩鼱；潑婦" },
    { en: "phew", zh: "呼！鬆一口氣" },
    { en: "crew", zh: "船員；工作人員" },
    { en: "pew", zh: "教堂長椅" },
    { en: "knew", zh: "知道（過去式）" },
    { en: "grew", zh: "成長（過去式）" },
    { en: "spew", zh: "噴出；嘔吐"
    }
  ]
},
{
  title: "ay ey oy",
  words: [
    { en: "prey", zh: "獵物；掠奪" },
    { en: "dray", zh: "運貨車" },
    { en: "Troy", zh: "特洛伊" },
    { en: "drey", zh: "松鼠巢" },
    { en: "flay", zh: "剝皮" },
    { en: "coy", zh: "靦腆的" },
{ en: "roy", zh: "羅伊（人名）" },
{ en: "bay", zh: "海灣" },
{ en: "gay", zh: "快樂的；同性戀的" },
{ en: "cloy", zh: "使厭膩" },
    { en: "whey", zh: "乳清" },
    { en: "fray", zh: "磨損；爭吵" },
{ en: "toy", zh: "玩具" },
{ en: "joy", zh: "喜悅" },
    { en: "ploy", zh: "策略；花招" },
{ en: "they", zh: "他們" },
{ en: "hey", zh: "嘿；喂" },
    { en: "slay", zh: "殺死" },
    { en: "stray", zh: "迷路；偏離" },
    { en: "splay", zh: "張開；伸展" },
{ en: "day", zh: "日子；白天" },
{ en: "way", zh: "方法；道路" },
    { en: "fey", zh: "怪異的" },
    { en: "soy", zh: "大豆" },
{ en: "ray", zh: "光線" },
{ en: "pay", zh: "付錢" },
{ en: "grey", zh: "灰色的" },
{ en: "may", zh: "可以；五月" },
{ en: "say", zh: "說" },
{ en: "lay", zh: "放置；產卵" },
{ en: "gray", zh: "灰色的" },
{ en: "spray", zh: "噴霧" },
{ en: "tray", zh: "托盤" },
    { en: "bray", zh: "驢叫聲"
    }
  ]
},
{
  title: "wa aw au al",
  words: [
    { en: "daub", zh: "塗抹；亂畫" },
    { en: "balk", zh: "猶豫；阻止" },
    { en: "flaw", zh: "缺陷" },
    { en: "wasp", zh: "黃蜂" },
    { en: "launch", zh: "發射；推出" },
    { en: "stalk", zh: "莖；跟蹤" },
    { en: "thaw", zh: "解凍" },
    { en: "swash", zh: "拍打；虛張聲勢" },
    { en: "fraud", zh: "詐騙" },
    { en: "thrall", zh: "奴役；迷住" },
    { en: "slaw", zh: "涼拌高麗菜" },
    { en: "swatch", zh: "樣本；布樣" },
    { en: "gaunt", zh: "消瘦的" },
    { en: "stall", zh: "攤位；拖延" },
    { en: "claw", zh: "爪" },
    { en: "swamp", zh: "沼澤；淹沒"
    }
  ]
},
{
  title: "oa old ild ind",
  words: [
    { en: "coach", zh: "教練" },
    { en: "scold", zh: "責罵" },
    { en: "rind", zh: "外皮" },
    { en: "mild", zh: "溫和的" },
    { en: "throat", zh: "喉嚨" },
    { en: "bold", zh: "大膽的" },
    { en: "hind", zh: "後面的" },
    { en: "shoal", zh: "魚群" },
    { en: "mold", zh: "黴菌" },
    { en: "bind", zh: "綁" },
    { en: "wild", zh: "野生的" },
    { en: "oath", zh: "誓言" },
    { en: "wold", zh: "荒原" },
    { en: "blind", zh: "失明的" },
    { en: "bloat", zh: "腫脹" },
    { en: "grind", zh: "研磨"
    }
  ]
},
{
  title: "oo ow",
  words: [
    { en: "scoot", zh: "快速移動" },
    { en: "soot", zh: "煤灰" },
    { en: "gown", zh: "長袍" },
    { en: "cr*ow", zh: "烏鴉" },
    { en: "broom", zh: "掃帚" },
    { en: "food", zh: "食物" },
    { en: "drown", zh: "溺水" },
    { en: "thr*ow", zh: "投擲" },
    { en: "drool", zh: "流口水" },
    { en: "stood", zh: "站立" },
    { en: "scowl", zh: "怒視" },
    { en: "st*ow", zh: "收起" },
    { en: "vroom", zh: "引擎聲" },
    { en: "rook", zh: "烏鴉" },
    { en: "b*ow", zh: "蝴蝶結"},
{ en: "moon", zh: "月亮" },
{ en: "spoon", zh: "湯匙" },
{ en: "pool", zh: "水池" },
{ en: "frown", zh: "皺眉" },
{ en: "tooth", zh: "牙齒" },
{ en: "growl", zh: "低吼" },
{ en: "hoot", zh: "鳴叫" },
{ en: "cool", zh: "涼爽的" },
{ en: "cow", zh: "牛" },
{ en: "howl", zh: "嚎叫" },
{ en: "owl", zh: "貓頭鷹" },
{ en: "brown", zh: "棕色" },
{ en: "clown", zh: "小丑" },
{ en: "boot", zh: "靴子" },
{ en: "fl*ow", zh: "流動" },
{ en: "loop", zh: "圈；環" },
{ en: "gl*ow", zh: "發光" },
{ en: "sl*ow", zh: "慢的" }
  ]
},
{
  title: "ear eer",
  words: [
    { en: "earl", zh: "伯爵" },
    { en: "smear", zh: "塗抹" },
    { en: "queer", zh: "奇怪的" },
    { en: "pearl", zh: "珍珠" },
    { en: "tear", zh: "眼淚；撕裂" },
    { en: "sneer", zh: "冷笑；嘲諷" },
    { en: "search", zh: "搜尋" },
    { en: "spear", zh: "矛" },
    { en: "sheer", zh: "陡峭的" },
    { en: "heard", zh: "聽到" },
    { en: "rear", zh: "後面的" },
    { en: "deer", zh: "鹿" },
    { en: "cheer", zh: "歡呼" },
    { en: "beer", zh: "啤酒" },
    { en: "jeer", zh: "嘲笑" },
    { en: "steer", zh: "駕駛"
    }
  ]
},
{
  title: "-y -ey",
  words: [
    { en: "fain.tly", zh: "微弱地" },
    { en: "phoo.ey", zh: "呸！" },
    { en: "lea.ky", zh: "漏水的" },
    { en: "tro.lley", zh: "手推車；電車" },
    { en: "taw.ny", zh: "黃褐色的" },
    { en: "pric.kly", zh: "多刺的" },
    { en: "lor.dly", zh: "高傲的" },
    { en: "per.ki.ly", zh: "活潑地" },
    { en: "shon.ky", zh: "劣質的" },
    { en: "twir.ly", zh: "旋轉的" },
    { en: "whin.ny", zh: "馬嘶聲" },
    { en: "ar.my", zh: "軍隊" },
    { en: "foa.my", zh: "起泡的" },
    { en: "i.tchy", zh: "痕癢的" },
    { en: "stic.ky", zh: "黏的"  },
{ en: "win.dy", zh: "有風的" },
{ en: "mud.dy", zh: "泥濘的" },
{ en: "jer.sey", zh: "澤西島" },
{ en: "ea.si.ly", zh: "容易地" },
{ en: "hoc.key", zh: "曲棍球" },
{ en: "chim.ney", zh: "煙囪" },
{ en: "kid.ney", zh: "腎臟" },
{ en: "emp.ty", zh: "空的" },
{ en: "an.gry", zh: "生氣的" },
{ en: "hun.gry", zh: "肚餓的" },
{ en: "si.lly", zh: "傻的" },
{ en: "mon.key", zh: "猴子" },
{ en: "don.key", zh: "驢" },
{ en: "noi.sy", zh: "嘈吵的" },
{ en: "tur.key", zh: "火雞" },
{ en: "quic.kly", zh: "快速地" },
{ en: "sto.ry", zh: "故事" }
  ]
},
{
  title: "ce ci cy",
  words: [
    { en: "cist", zh: "石棺" },
    { en: "puce", zh: "暗紅色" },
    { en: "cy.nic", zh: "憤世嫉俗的人" },
    { en: "cite", zh: "引用" },
    { en: "cede", zh: "割讓"},

    { en: "sau.cy", zh: "無禮的" },
    { en: "cinch", zh: "容易的事" },
    { en: "mace", zh: "權杖" },
    { en: "fan.cy", zh: "花俏的" },
    { en: "cig", zh: "香煙" },

    { en: "choice", zh: "選擇" },
    { en: "force", zh: "力量" },
    { en: "face", zh: " 臉" },
    { en: "rice", zh: "米飯" },
    { en: "fence", zh: "圍欄" },
    { en: "space", zh: "空間" },
    { en: "dice", zh: "骰子"
    }
  ]
},
{
  title: "ge dge",
  words: [
    { en: "gem", zh: "寶石" },
    { en: "barge", zh: "駁船" },
    { en: "smudge", zh: "污漬" },
    { en: "gel", zh: "凝膠" },
    { en: "binge", zh: "暴飲暴食" },
    { en: "budge", zh: "挪動" },
    { en: "germ", zh: "細菌" },
    { en: "bilge", zh: "船艙污水" },
    { en: "edge", zh: "邊緣" },
    { en: "gene", zh: "基因" },
    { en: "forge", zh: "鍛造；偽造" },
    { en: "lodge", zh: "小屋；投宿" },
    { en: "purge", zh: "清除" },
    { en: "nudge", zh: "輕推" },
    { en: "splodge", zh: "一大灘污漬"  },
{ en: "badge", zh: "徽章" },
{ en: "rage", zh: "憤怒" },
{ en: "bridge", zh: "橋" },
{ en: "wage", zh: "工資" },
{ en: "ridge", zh: "山脊" },
{ en: "judge", zh: "法官" },
{ en: "page", zh: "頁" },
{ en: "hedge", zh: "樹籬" },
{ en: "wedge", zh: "楔子" },
{ en: "trudge", zh: "艱難行走" },
{ en: "pledge", zh: "保證；誓言" },
{ en: "age", zh: "年齡" },
{ en: "cage", zh: "籠子" },
{ en: "huge", zh: "巨大的" },
{ en: "fudge", zh: "軟糖；含糊其辭" },
{ en: "grudge", zh: "怨恨" },
{ en: "sage", zh: "智者；鼠尾草" }
  ]
},
{
  title: "gh igh ight ou ought",
  words: [
    { en: "sought", zh: "尋找" },
    { en: "gout", zh: "痛風" },
    { en: "sight", zh: "視力" },
    { en: "sigh", zh: "嘆氣" },

    { en: "bough", zh: "樹枝" },
    { en: "wrought", zh: "鍛造的" },
    { en: "spout", zh: "噴口" },
    { en: "plight", zh: "困境" },

    { en: "thigh", zh: "大腿" },
    { en: "fraught", zh: "充滿壓力的" },
    { en: "nought", zh: "零" },
    { en: "crouch", zh: "蹲下" },

    { en: "plough", zh: "犁" },
    { en: "knight", zh: "騎士" },
    { en: "sleigh", zh: "雪橇" },

    { en: "weight", zh: "重量" },
    { en: "thought", zh: "想法" },
    { en: "flight", zh: "飛行" },
    { en: "tight", zh: "緊的"
    }
  ]
},
{
  title: "are air",
  words: [
    { en: "hare", zh: "野兔" },
    { en: "mare", zh: "母馬" },
    { en: "flair", zh: "天賦；風格" },
    { en: "blare", zh: "刺耳的聲音" },

    { en: "snare", zh: "陷阱；誘捕" },
    { en: "laird", zh: "地主" },
    { en: "tare", zh: "皮重" },

    { en: "lair", zh: "巢穴" },
    { en: "glare", zh: "怒視" },
    { en: "rare", zh: "稀有的" },

    { en: "stare", zh: "凝視" },
    { en: "scare", zh: "驚嚇" },
    { en: "spare", zh: "多餘的"},
{ en: "care", zh: "照顧；小心" },
{ en: "square", zh: "正方形" },
{ en: "dare", zh: "敢於" },
{ en: "fare", zh: "車費；票價" },
{ en: "bare", zh: "赤裸的" },
{ en: "ware", zh: "器皿；製品" },
{ en: "share", zh: "分享" },
{ en: "chair", zh: "椅子" },
{ en: "pair", zh: "一對" },
{ en: "fair", zh: "公平的；市集" },
{ en: "hair", zh: "頭髮" },
{ en: "stair", zh: "樓梯" }
  ]
},
{
  title: "wor oar",
  words: [
    { en: "wort", zh: "麥芽汁" },
    { en: "hoarse", zh: "聲音沙啞的" },
    { en: "world", zh: "世界" },
    { en: "soar", zh: "高飛" },

    { en: "worm", zh: "蠕蟲" },
    { en: "oar", zh: "船槳" },
    { en: "work", zh: "工作" },

    { en: "boar", zh: "野豬" },
    { en: "word", zh: "單字" },
    { en: "roar", zh: "咆哮" },

    { en: "worth", zh: "價值" },
    { en: "coarse", zh: "粗糙的" },
    { en: "worse", zh: "更差的" },
    { en: "hoard", zh: "囤積" },
{ en: "wor.ry", zh: "擔心" },
{ en: "worst", zh: "最差的" },
{ en: "wor.thy", zh: "值得的" }
  ]
},

{
  title: "ire war",
  words: [
    { en: "tire", zh: "輪胎" },
    { en: "ward", zh: "病房" },
    { en: "spire", zh: "尖塔" },
    { en: "warp", zh: "扭曲" },
    { en: "quire", zh: "一疊紙" },
    { en: "wart", zh: "疣" },
    { en: "shire", zh: "郡" },
{ en: "warfare", zh: "戰爭行動" },
    { en: "swar.thy", zh: "黝黑的" },
    { en: "squire", zh: "鄉紳；侍從" },
    { en: "thwart", zh: "阻撓" },
    { en: "mire", zh: "泥沼" },
    { en: "dwarf", zh: "矮人" },
    { en: "em.pire", zh: "帝國" },
    { en: "swarm", zh: "蜂群" },
    { en: "swarf", zh: "金屬屑" },
{ en: "war", zh: "戰爭" },
{ en: "fire", zh: "火" },
{ en: "dire", zh: "嚴重的" },
{ en: "in.spire", zh: "啟發" },
{ en: "warm", zh: "溫暖的" },
{ en: "warn", zh: "警告" },
{ en: "war.ning", zh: "警告；警示" },
{ en: "wire", zh: "電線" },
{ en: "war.lord", zh: "軍閥" },
{ en: "hire", zh: "僱用；租用" },
{ en: "war.drobe", zh: "衣櫃" }
  ]
},
{
  title: "-er -or -ar -a",
  words: [
    { en: "dow.er", zh: "嫁妝" },
    { en: "vic.tor", zh: "勝利者" },
    { en: "al.tar", zh: "祭壇" },
    { en: "qui.ver", zh: "顫抖" },
    { en: "air.er", zh: "晾衣架" },
    { en: "cen.sor", zh: "審查" },
    { en: "mor.tar", zh: "灰泥" },
    { en: "cir.ca", zh: "大約" },
    { en: "cin.der", zh: "煤渣" },
    { en: "bai.lor", zh: "舀水器" },
    { en: "lar.va", zh: "幼蟲" },
    { en: "sau.cer", zh: "茶碟" },
    { en: "tur.gor", zh: "膨壓" },
    { en: "a.qua", zh: "水" },
    { en: "wan.der", zh: "漫遊" },
    { en: "au.thor", zh: "作者" }
  ]
},

{
  title: "-age -ket -pet",
  words: [
{ en: "voy.age", zh: "航行；旅程" },
{ en: "ma.nage", zh: "管理；設法做到" },
{ en: "poc.ket", zh: "口袋" },
{ en: "roc.ket", zh: "火箭" },
{ en: "tic.ket", zh: "票" },
{ en: "jac.ket", zh: "外套" },
{ en: "buc.ket", zh: "水桶" },
{ en: "rac.ket", zh: "球拍；吵鬧聲" },
{ en: "soc.ket", zh: "插座" },
{ en: "brac.ket", zh: "括號；支架" },
{ en: "loc.ket", zh: "小吊墜盒" },
{ en: "pac.ket", zh: "小包" },
{ en: "sproc.ket", zh: "鏈輪" },
{ en: "mu.sket", zh: "滑膛槍" },
{ en: "trin.ket", zh: "小飾物" },
{ en: "ca.sket", zh: "小盒；棺材" },
{ en: "vi.llage", zh: "村莊" },
{ en: "lug.gage", zh: "行李" },
{ en: "ban.dage", zh: "繃帶" },
{ en: "ho.stage", zh: "人質" },
{ en: "shor.tage", zh: "短缺" },
{ en: "pas.sage", zh: "通道；段落" },
{ en: "cot.tage", zh: "小屋" },
{ en: "pac.kage", zh: "包裹" },
{ en: "da.mage", zh: "損壞" },
{ en: "mes.sage", zh: "訊息" }
  ]
},

{
  title: "tion sion",
  words: [
{ en: "ac.tion", zh: "行動" },
{ en: "vi.sion", zh: "視力；視野" },
{ en: "fic.tion", zh: "小說；虛構作品" },
{ en: "op.tion", zh: "選擇" },
{ en: "cap.tion", zh: "標題說明" },
{ en: "sec.tion", zh: "部分" },
{ en: "men.tion", zh: "提及" },
{ en: "cau.tion", zh: "小心；警告" },
{ en: "por.tion", zh: "份量" },
{ en: "pas.sion", zh: "熱情" },
{ en: "ten.sion", zh: "緊張；拉力" },
{ en: "mis.sion", zh: "任務" },
{ en: "in.fec.tion", zh: "感染" },
{ en: "in.spec.tion", zh: "檢查" },
{ en: "auc.tion", zh: "拍賣" },
{ en: "im.mer.sion", zh: "沉浸" },
{ en: "in.cur.sion", zh: "侵入" },
{ en: "in.ci.sion", zh: "手術切口" },
{ en: "ses.sion", zh: "會議" }
  ]
},

{
  title: "-ow -o",
  words: [
{ en: "win.dow", zh: "窗戶" },
{ en: "ye.llow", zh: "黃色" },
{ en: "fo.llow", zh: "跟隨" },
{ en: "sha.dow", zh: "影子" },
{ en: "na.rrow", zh: "狹窄的" },
{ en: "a.rrow", zh: "箭" },
{ en: "el.bow", zh: "手肘" },
{ en: "al.so", zh: "也" },
{ en: "me.mo", zh: "備忘錄" },
{ en: "de.mo", zh: "示範；演示" },
{ en: "ta.co", zh: "墨西哥夾餅" },
{ en: "na.cho", zh: "玉米片" },
{ en: "man.go", zh: "芒果" },
{ en: "pi.llow", zh: "枕頭" },
{ en: "bo.rrow", zh: "借" },
{ en: "car.go", zh: "貨物" },
{ en: "tur.bo", zh: "渦輪增壓" },
{ en: "in.tro", zh: "介紹；開場白" },
{ en: "ma.cro", zh: "宏觀的" },
{ en: "au.di.o", zh: "聲音的" },
{ en: "bra.vo", zh: "喝采" }
  ]
},

{
  title: "-el -le -al",
  words: [
{ en: "tun.nel", zh: "隧道" },
{ en: "ca.mel", zh: "駱駝" },
{ en: "mo.del", zh: "模型；模特兒" },
{ en: "pa.nel", zh: "面板" },
{ en: "an.gel", zh: "天使" },
{ en: "tra.vel", zh: "旅行" },
{ en: "ap.ple", zh: "蘋果" },
{ en: "lit.tle", zh: "小的" },
{ en: "sim.ple", zh: "簡單的" },
{ en: "pur.ple", zh: "紫色" },
{ en: "un.cle", zh: "叔叔；伯父" },
{ en: "cir.cle", zh: "圓形" },
{ en: "a.ni.mal", zh: "動物" },
{ en: "me.tal", zh: "金屬" },
{ en: "roy.al", zh: "皇家的" },
{ en: "le.vel", zh: "水平；等級" },
{ en: "no.vel", zh: "小說" },
{ en: "vow.el", zh: "母音" },
{ en: "cha.pel", zh: "小教堂" },
{ en: "ba.rrel", zh: "桶" },
{ en: "can.cel", zh: "取消" },
{ en: "par.cel", zh: "包裹" },
{ en: "ea.gle", zh: "老鷹" },
{ en: "bee.tle", zh: "甲蟲" },
{ en: "bot.tle", zh: "瓶子" },
{ en: "bub.ble", zh: "氣泡" },
{ en: "sig.nal", zh: "訊號" },
{ en: "me.dal", zh: "獎牌" },
{ en: "pe.dal", zh: "腳踏板" },
{ en: "co.ral", zh: "珊瑚" }
  ]
},

{
  title: "ture",
  words: [
{ en: "picture", zh: "圖畫；照片" },
{ en: "culture", zh: "文化" },
{ en: "capture", zh: "捕捉" },
{ en: "mixture", zh: "混合物" },
{ en: "feature", zh: "特徵" },
{ en: "creature", zh: "生物" },
{ en: "lecture", zh: "講座" },
{ en: "structure", zh: "結構" },
{ en: "fracture", zh: "骨折；斷裂" },
{ en: "gesture", zh: "手勢" },
{ en: "posture", zh: "姿勢" },
{ en: "rapture", zh: "狂喜" },
{ en: "sculpture", zh: "雕塑" },
{ en: "furniture", zh: "家具" },
{ en: "moisture", zh: "濕氣" },
{ en: "vulture", zh: "禿鷹" }

  ]
},

{
  title: "ed",
  words: [
{ en: "jumped", zh: "跳了" },
{ en: "nee.ded", zh: "需要了" },
{ en: "pain.ted", zh: "油漆了" },
{ en: "helped", zh: "幫助了" },
{ en: "looked", zh: "看了" },
{ en: "cleaned", zh: "清潔了" },
{ en: "shou.ted", zh: "喊叫了" },
{ en: "washed", zh: "洗了" },
{ en: "closed", zh: "關上了" },
{ en: "wan.ted", zh: "想要了" },
{ en: "star.ted", zh: "開始了" },
{ en: "visi.ted", zh: "拜訪了" },
{ en: "played", zh: "玩了" },
{ en: "hea.ted", zh: "加熱了" },
{ en: "wai.ted", zh: "等待了" },
{ en: "ac.ted", zh: "表演了" },
{ en: "ad.ded", zh: "加了" },
{ en: "en.ded", zh: "結束了" }

  ]
},

{
  title: "unstressed a e i o u",
  words: [
{ en: "ban.tam", zh: "矮腳雞（矮種雞）" },
{ en: "bat.ten", zh: "板條；用板條固定" },
{ en: "vo.mit", zh: "嘔吐" },
{ en: "tar.tan", zh: "蘇格蘭格子布" },
{ en: "an.trum", zh: "竇；胃竇" },
{ en: "fun.dus", zh: "底部；（眼/胃）底" },
{ en: "an.them", zh: "國歌；頌歌" },
{ en: "for.tress", zh: "堡壘" },
{ en: "sy.rup", zh: "糖漿" },
{ en: "se.cond", zh: "第二；秒" },
{ en: "daf.fo.dil", zh: "水仙花" },
{ en: "an.to.nym", zh: "反義詞" },
{ en: "phar.ma.cy", zh: "藥房" },
{ en: "re.mi.nisce", zh: "回憶；追憶" },
{ en: "in.fi.ni.ty", zh: "無限" },
{ en: "in.te.gri.ty", zh: "正直；誠信" },
{ en: "con.si.stent", zh: "一致的" },
{ en: "po.rridge", zh: "粥；麥片粥" },
{ en: "ar.ma.ture", zh: "骨架；電樞" },
{ en: "Ja.mai.ca", zh: "牙買加" },
{ en: "por.ta.ble", zh: "便攜的" },
{ en: "to.bac.co", zh: "煙草" },
{ en: "se.na.tor", zh: "參議員" },
{ en: "con.cer.to", zh: "協奏曲" },
{ en: "su.rren.der", zh: "投降" },
{ en: "Ra.pun.zel", zh: "長髮公主" },
{ en: "ar.ma.di.llo", zh: "犰狳" },
{ en: "at.tend", zh: "出席；參加" },
{ en: "a.wake", zh: "醒著的" },
{ en: "mi.lli.on", zh: "一百萬" },
{ en: "op.pose", zh: "反對" },
{ en: "ob.tain", zh: "得到" },
{ en: "o.pi.ni.on", zh: "意見" },
{ en: "un.safe", zh: "不安全" },
{ en: "um.bre.lla", zh: "雨傘" },
{ en: "ad.ven.ture", zh: "冒險" },
{ en: "e.rupt", zh: "爆發；噴發" },
{ en: "en.joy", zh: "享受" },
{ en: "re.peat", zh: "重複" },
{ en: "e.merge", zh: "出現；浮現" },
{ en: "de.lete", zh: "刪除" },
{ en: "pre.pare", zh: "準備" },
{ en: "be.fore", zh: "之前" }

  ]
},

{
  title: "Syllable Division (VCV VCCV)",
  words: [
{ en: "cactus", zh: "仙人掌" },
{ en: "sunlit", zh: "被陽光照亮的" },
{ en: "coffin", zh: "棺材" },
{ en: "summit", zh: "山頂；高峰" },
{ en: "bantam", zh: "矮種雞" },
{ en: "wanton", zh: "放縱的；肆意的" },
{ en: "pecten", zh: "扇貝" },
{ en: "ditto", zh: "同上；一樣" },
{ en: "crimson", zh: "深紅色" },
{ en: "lemon", zh: "檸檬" },
{ en: "denim", zh: "牛仔布" },
{ en: "famish", zh: "使飢餓" },
{ en: "column", zh: "欄；柱子" },
{ en: "abyss", zh: "深淵" },
{ en: "agony", zh: "極度痛苦" },
{ en: "prolific", zh: "多產的；豐富的" },
{ en: "dissident", zh: "持不同政見者" },
{ en: "cinnamon", zh: "肉桂" },
{ en: "pivotal", zh: "關鍵的" }

  ]
},

{
  title: "Syllable Division (digraph)",
  words: [
{ en: "satchel", zh: "書包；皮包" },
{ en: "cocoon", zh: "繭" },
{ en: "custody", zh: "監護；拘留" },
{ en: "laurel", zh: "月桂" },
{ en: "ethnic", zh: "種族的；民族的" },
{ en: "coastal", zh: "沿海的" },
{ en: "lagoon", zh: "潟湖" },
{ en: "amethyst", zh: "紫水晶" },
{ en: "charcoal", zh: "木炭" },
{ en: "artichoke", zh: "朝鮮薊" },
{ en: "testimony", zh: "證詞" },
{ en: "statistics", zh: "統計學" },
{ en: "hibiscus", zh: "木槿；扶桑花" },
{ en: "byzantine", zh: "拜占庭的；錯綜複雜的" }

  ]
},

{
  title: "Syllable Division (Cr Cl)",
  words: [
{ en: "tantra", zh: "密宗修行法；坦陀羅" },
{ en: "laundry", zh: "洗衣；洗衣房" },
{ en: "antrum", zh: "竇；腔室" },
{ en: "fabric", zh: "布料；織物" },
{ en: "aggro", zh: "挑釁" },
{ en: "pantry", zh: "食品儲藏室" },
{ en: "atlas", zh: "地圖冊" },
{ en: "goblet", zh: "高腳杯" },
{ en: "emblem", zh: "徽章；象徵" },
{ en: "peplum", zh: "裙擺上衣；短裙裝飾" },
{ en: "paisley", zh: "變形蟲花紋" },
{ en: "muslin", zh: "細棉布" },
{ en: "astral", zh: "星體的；星界的" },
{ en: "goblin", zh: "小妖精" },
{ en: "ministry", zh: "部門；事工" },
{ en: "cockroach", zh: "蟑螂" },
{ en: "sacrament", zh: "聖禮" },
{ en: "contradict", zh: "反駁；矛盾" }

  ]
},


{
  title: "Syllable Division (ll rr)",
  words: [
{ en: "gallop", zh: "（馬）飛奔" },
{ en: "furrow", zh: "皺紋；犁溝" },
{ en: "vanilla", zh: "雲呢拿；香草味" },
{ en: "burrow", zh: "地洞；挖洞" },
{ en: "carrot", zh: "紅蘿蔔" },
{ en: "sporran", zh: "蘇格蘭毛皮小袋" },
{ en: "mallee", zh: "澳洲桉樹叢" },
{ en: "sorrow", zh: "悲傷" },
{ en: "ballot", zh: "投票；選票" },
{ en: "stirrup", zh: "馬鐙" },
{ en: "horror", zh: "恐怖" },
{ en: "shallow", zh: "淺的" },
{ en: "wallow", zh: "打滾；沉溺" },
{ en: "Ferris", zh: "摩天輪" },
{ en: "chancellor", zh: "大臣；財政大臣" },
{ en: "trillion", zh: "兆（萬億）" }

  ]
},


{
  title: "Open Syllable (2)",
  words: [
{ en: "-open", zh: "打開的；公開的" },
{ en: "n-avy", zh: "海軍" },
{ en: "ph-ial", zh: "小瓶" },
{ en: "p-upal", zh: "蛹的；蛹期的" },
{ en: "m-atron", zh: "女舍監；護士長" },
{ en: "r-ival", zh: "對手" },
{ en: "b-ison", zh: "野牛" },
{ en: "c-yclone", zh: "氣旋；颶風" },
{ en: "r-ifle", zh: "步槍" },
{ en: "C-yprus", zh: "塞浦路斯" },
{ en: "c-edar", zh: "雪松" },
{ en: "b-ugle", zh: "號角" },
{ en: "c-ubicle", zh: "小隔間；辦公隔間" },
{ en: "s-epia", zh: "棕褐色" },
{ en: "carn-ation", zh: "康乃馨" },
{ en: "h-yacinth", zh: "風信子" },
{ en: "cam-ellia", zh: "山茶花" },
{ en: "torn-ado", zh: "龍捲風" }

  ]
},


];
